version: '3.8'
services:
  postgres-dev-server:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest-songs
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bookmarks

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres-dev-server
    depends_on:
      - postgres-dev-server
    networks:
      - bookmarks

volumes:
  postgres-data:

networks:
  bookmarks: