### SEND FETCH SONGS REQUEST
GET  http://localhost:3000/songs

### FIND SONG BY ID
GET  http://localhost:3000/songs/10

### CREATE NEW SONG
POST   http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Lasting Lover",
    "artists": ["Sigla"],
    "releasedDate": "2022-09-02",
    "duration": "02:34"
}

### EDIT A SONG
PATCH   http://localhost:3000/songs/1
Content-Type: application/json

{
    "title": "Lasting",
    "artists": ["Sigla"],
    "releasedDate": "2022-09-02",
    "duration": "02:34"
}

### DELETE A SONG
DELETE  http://localhost:3000/songs/1
