### SEND FETCH SONGS REQUEST
GET  http://localhost:3000/songs?limit=10&page=1&search=Lover

### FIND SONG BY ID
GET  http://localhost:3000/songs/10

### CREATE NEW SONG
POST   http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Lasting Lover 2",
    "artists": ["Sigla 2"],
    "releasedDate": "2022-09-02",
    "duration": "02:34"
}

### EDIT A SONG
PATCH   http://localhost:3000/songs/1
Content-Type: application/json

{
    "title": "Lasting Edited Again",
    "artists": ["Sigla Edited"],
    "releasedDate": "2022-09-03",
    "duration": "02:33"
}

### DELETE A SONG
DELETE  http://localhost:3000/songs/1
